x-templates:
    template-service: &template-service
        restart: unless-stopped
        pull_policy: ${PULL_POLICY:-always}
        mem_limit: 2G
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"

services:

    traccar-server:
        <<: *template-service
        container_name: traccar-server
        build: .
        depends_on:
            - traccar-server-database
        mem_limit: 1G
        environment:
            - DATABASE_PASSWORD=secret
            - DATABASE_URL=postgresql://traccar-server-database/database
            - DATABASE_USERNAME=traccar
            - FILTER_ACCURACY=100
            - FILTER_SKIP_LIMIT=3600
            - FRONTEND_URL=http://localhost:8000
            # - OIDC_ADMIN_GROUP=admin
            # - OIDC_CLIENT_ID=traccar
            # - OIDC_CLIENT_SECRET=
            # - OIDC_FORCE=true
            # - OIDC_ISSUER_URL=https://keycloak/realms/dev
        ports:
            - 127.0.0.1:8000:80

    traccar-server-database:
        <<: *template-service
        image: postgres:18
        mem_limit: 500M
        environment:
            - POSTGRES_DB=database
            - POSTGRES_PASSWORD=secret
            - POSTGRES_USER=traccar
        volumes:
            - ./data-local/database:/var/lib/postgresql
        expose:
            - "5432"
