version: "3.8"

x-templates:
    template-service: &template-service
        restart: unless-stopped
        pull_policy: always

services:

    traccar-server:
        <<: *template-service
        container_name: traccar-server
        build: .
        depends_on:
            - traccar-server-database
        environment:
            - DATABASE_PASSWORD=secret
            - DATABASE_URL=postgresql://traccar-server-database/database
            - DATABASE_USERNAME=traccar
            - FRONTEND_URL=http://localhost:8000
        ports:
            - 8000:80

    traccar-server-database:
        <<: *template-service
        image: postgres:16
        environment:
            - POSTGRES_DB=database
            - POSTGRES_PASSWORD=secret
            - POSTGRES_USER=traccar
        volumes:
            - ./data-local/database:/var/lib/postgresql/data
        expose:
            - "5432"
